=== andyw23/infinity/scores.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.w3schools.com"
        xmlns="https://www.w3schools.com"
        elementFormDefault="qualified">

    <xs:element name="program">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="xmlns" type="xs:string" use="required"/>
            <xs:attribute name="xmlns:xsi" type="xs:string" use="required"/>
            <xs:attribute name="xsi:schemaLocation" type="xs:string" use="required"/>
            <xs:sequence>
                <xs:element name="components">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sample" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="file" type="xs:string" use="required"/>
                                    <xs:attribute name="length" type="xs:string" use="required"/>
                                    <xs:sequence>
                                        <xs:element name="variant"
                                                    maxOccurs="unbounded"
                                                    minOccurs="1">
                                            <xs:complexType>
                                                <xs:attribute name="id"
                                                              type="xs:string"
                                                              use="required"/>
                                                <xs:sequence>
                                                    <xs:element name="loopcount"
                                                                type="xs:int"/>
                                                    <xs:element name="loopstarttime"
                                                                type="xs:string"/>
                                                    <xs:element name="loopendtime"
                                                                type="xs:int"/>
                                                    <xs:element name="looplength"
                                                                type="xs:string"/>
                                                    <xs:element name="dynamics"
                                                                maxOccurs="unbounded"
                                                                minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="instruction"
                                                                            maxOccurs="unbounded"
                                                                            minOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="time"
                                                                                      type="xs:string"
                                                                                      use="optional"/>
                                                                        <xs:attribute name="level"
                                                                                      type="xs:int"
                                                                                      use="optional" default="0">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:int">
                                                                                    <xs:minInclusive value="0"/>
                                                                                    <xs:maxInclusive value="255"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>

                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="concert" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" use="required"/>
                                    <xs:sequence>
                                        <xs:element name="part" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="id" use="required"/>
                                                <xs:attribute name="variant" use="optional"/>
                                                <xs:attribute name="start" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="choose" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" use="required"/>
                                    <xs:sequence>
                                        <xs:element name="part" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="id" use="required"/>
                                                <xs:attribute name="variant" use="optional"/>
                                                <xs:attribute name="start" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="scores" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="score" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" use="required"/>
                                    <xs:sequence>
                                        <xs:element name="create" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:attribute name="id" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== andyw23/infinity/scores.xml
<?xml version="1.0"?>

<program name="Tim 16" xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com scores.xsd">
    <components>
        <sample id="A" file="A01" length="25.2130">
            <variant id="1">
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="150"/>
                </dynamics>
            </variant>
            <variant id="2">
                <loopstarttime>0</loopstarttime>
                <loopendtime>10000</loopendtime>
                <dynamics>
                    <instruction time="0" level="200"/>
                </dynamics>
            </variant>
        </sample>
        <sample id="altai dopsh" file="altai dopsh" length="81.4400">
            <variant id="1">
                <loopstarttime>12899</loopstarttime>
                <loopendtime>81420</loopendtime>
                <loopcount>0</loopcount>
                <!--looplength>2:20</looplength-->
                <looplength>2:10</looplength>
                <dynamics>
                    <instruction time="0" level="0"/>
                    <instruction time="0:10" level="100"/>
                    <instruction time="1:55" level="100"/>
                    <!--instruction time="2.10" level="0"/-->
                </dynamics>
            </variant>
            <variant id="2">
                <loopstarttime>12899</loopstarttime>
                <loopendtime>81420</loopendtime>
                <loopcount>0</loopcount>
                <!--looplength>1:30</looplength-->
                <looplength>1:20</looplength>
                <dynamics>
                    <instruction time="0" level="0"/>
                    <instruction time="0:15" level="100"/>
                    <instruction time="1:05" level="100"/>
                    <!--instruction time="1.20" level="0"/-->
                </dynamics>
            </variant>
            <variant id="3">
                <loopstarttime>26000</loopstarttime>
                <loopendtime>50000</loopendtime>
                <loopcount>0</loopcount>
                <!--looplength>1:45</looplength-->
                <looplength>1:42</looplength>
                <dynamics>
                    <instruction time="0" level="0"/>
                    <instruction time="0:10" level="80"/>
                    <instruction time="1:24" level="80"/>
                    <!--instruction time="1.42" level="0"/-->
                </dynamics>
            </variant>
        </sample>
        <sample id="B" file="B01" length="54.0260">
            <variant id="1">
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="96"/>
                </dynamics>
            </variant>
            <variant id="2">
                <loopcount>0</loopcount>
                <looplength>0:05</looplength>
                <dynamics>
                    <instruction time="0" level="96"/>
                </dynamics>
            </variant>
            <variant id="3">
                <loopstarttime>0</loopstarttime>
                <loopendtime>50000</loopendtime>
                <dynamics>
                    <instruction time="0" level="96"/>
                    <instruction time="0:30" level="96"/>
                    <instruction time="0:40" level="20"/>
                    <instruction time="0:45" level="1"/>
                </dynamics>
            </variant>
            <variant id="4">
                <loopcount>0</loopcount>
                <looplength>1:21</looplength>
                <dynamics>
                    <instruction time="0" level="96"/>
                </dynamics>
            </variant>
        </sample>
        <sample id="BAS 1" file="BAS 1" length="1170.0130">
            <variant id="1">
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="180"/>
                </dynamics>
            </variant>
            <variant id="2">
                <loopstarttime>612500</loopstarttime>
                <dynamics>
                    <instruction time="0" level="180"/>
                </dynamics>
            </variant>
            <variant id="3">
                <loopstarttime>0</loopstarttime>
                <loopendtime>609000</loopendtime>
                <dynamics>
                    <instruction time="0" level="255"/>
                    <instruction time="0:49" level="255"/>
                    <instruction time="0:59" level="180"/>
                    <instruction time="2:10" level="255"/>
                    <instruction time="3:49" level="255"/>
                    <instruction time="3:58" level="180"/>
                    <instruction time="3:50" level="0"/>
                    <!--instruction time="3.57" level="0"/-->
                    <instruction time="3:59" level="180"/>
                    <instruction time="5:25" level="180"/>
                    <instruction time="5:40" level="255"/>
                    <instruction time="6:40" level="255"/>
                    <instruction time="6:54" level="180"/>
                    <instruction time="7:05" level="180"/>
                    <instruction time="7:20" level="220"/>
                    <instruction time="8:10" level="220"/>
                    <instruction time="8:25" level="180"/>
                </dynamics>
            </variant>
            <variant id="breath">
                <loopstarttime>107000</loopstarttime>
                <loopendtime>114000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="250"/>
                </dynamics>
            </variant>
            <variant id="cello">
                <loopstarttime>129100</loopstarttime>
                <loopendtime>230000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="255"/>
                </dynamics>
            </variant>
            <variant id="cello 2">
                <loopstarttime>174500</loopstarttime>
                <loopendtime>230000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="255"/>
                </dynamics>
            </variant>
            <variant id="ken vox">
                <loopstarttime>82000</loopstarttime>
                <loopendtime>115500</loopendtime>
                <loopcount>0</loopcount>
                <looplength>3:40</looplength>
                <dynamics>
                    <instruction time="0" level="60"/>
                </dynamics>
            </variant>
            <variant id="ken solo">
                <loopstarttime>59000</loopstarttime>
                <loopendtime>132000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="180"/>
                    <instruction time="1:05" level="180"/>
                    <instruction time="1:12" level="0"/>
                </dynamics>
            </variant>
            <variant id="oc solo">
                <loopstarttime>4000</loopstarttime>
                <loopendtime>57000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="180"/>
                </dynamics>
            </variant>
            <variant id="dung">
                <loopstarttime>341000</loopstarttime>
                <loopendtime>347000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="190"/>
                </dynamics>
            </variant>
            <variant id="split 1">
                <loopstarttime>0</loopstarttime>
                <loopendtime>58000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="250"/>
                </dynamics>
            </variant>
            <variant id="split 2">
                <loopstarttime>59000</loopstarttime>
                <loopendtime>112500</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="180"/>
                    <instruction time="0:27" level="180"/>
                    <instruction time="0:45" level="250"/>
                </dynamics>
            </variant>
            <variant id="split 3">
                <loopstarttime>111000</loopstarttime>
                <loopendtime>230000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="250"/>
                </dynamics>
            </variant>
            <variant id="split 4">
                <loopstarttime>236500</loopstarttime>
                <loopendtime>427000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="250"/>
                    <instruction time="0:15" level="180"/>
                    <instruction time="1:40" level="180"/>
                    <instruction time="1:55" level="250"/>
                    <instruction time="3:00" level="250"/>
                    <instruction time="3:07" level="0"/>
                </dynamics>
            </variant>
            <variant id="split 5">
                <loopstarttime>443000</loopstarttime>
                <loopendtime>555000</loopendtime>
                <loopcount>1</loopcount>
                <dynamics>
                    <instruction time="0" level="250"/>
                    <instruction time="1:33" level="250"/>
                    <instruction time="1:48" level="180"/>
                </dynamics>
            </variant>
            <variant id="split 6">
                <loopstarttime>554000</loopstarttime>
